/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * RSS Summarizer API
 * OpenAPI spec version: 1.0.0
 */
import { customFetch } from './client';

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;

export type ArticleResponseKeyPoints = string[] | null;

export type ArticleResponseTopics = string[] | null;

export interface ArticleResponse {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  created_at: string;
  /** Gmail message ID for email-sourced articles */
  email_message_id?: string;
  /** Email source ID (null for RSS-sourced articles) */
  email_source_id?: string;
  /** RSS feed ID (null for email-sourced articles) */
  feed_id?: string;
  id: string;
  importance_score?: number;
  is_archived: boolean;
  is_read: boolean;
  is_saved: boolean;
  key_points?: ArticleResponseKeyPoints;
  processing_error?: string;
  processing_status: string;
  published_at?: string;
  /** Source type: 'rss' or 'email' */
  source_type: string;
  summary?: string;
  title: string;
  topics?: ArticleResponseTopics;
  updated_at: string;
  url: string;
}

/**
 * Array of article IDs
 * @minItems 1
 * @maxItems 100
 */
export type BulkMarkReadRequestBodyArticleIds = string[] | null;

export interface BulkMarkReadRequestBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /**
   * Array of article IDs
   * @minItems 1
   * @maxItems 100
   */
  article_ids: BulkMarkReadRequestBodyArticleIds;
  /** Read status to set */
  is_read: boolean;
}

export interface BulkMarkReadResponseBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  updated: number;
}

/**
 * Array of article IDs
 * @minItems 1
 * @maxItems 100
 */
export type BulkSetArchivedRequestBodyArticleIds = string[] | null;

export interface BulkSetArchivedRequestBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /**
   * Array of article IDs
   * @minItems 1
   * @maxItems 100
   */
  article_ids: BulkSetArchivedRequestBodyArticleIds;
  /** Archived status to set */
  is_archived: boolean;
}

/**
 * Array of article IDs
 * @minItems 1
 * @maxItems 100
 */
export type BulkSetSavedRequestBodyArticleIds = string[] | null;

export interface BulkSetSavedRequestBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /**
   * Array of article IDs
   * @minItems 1
   * @maxItems 100
   */
  article_ids: BulkSetSavedRequestBodyArticleIds;
  /** Saved status to set */
  is_saved: boolean;
}

export interface ConnectGmailResponseBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Gmail OAuth authorization URL */
  auth_url: string;
}

export interface CreateFeedRequestBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /**
   * Polling frequency in minutes
   * @minimum 15
   * @maximum 1440
   */
  poll_frequency_minutes: number;
  /**
   * RSS feed URL
   * @pattern ^https?://.+
   */
  url: string;
}

export interface CreateNewsletterFilterRequestBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Email source ID */
  email_source_id: string;
  /**
   * Gmail label or Outlook folder
   * @maxLength 255
   */
  label_or_folder?: string;
  /**
   * Filter name
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  /**
   * Sender pattern (e.g., *@substack.com)
   * @minLength 1
   * @maxLength 500
   */
  sender_pattern: string;
  /**
   * Optional subject regex pattern
   * @maxLength 500
   */
  subject_pattern?: string;
}

export interface CreateTopicRequestBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /**
   * Topic name
   * @minLength 1
   * @maxLength 255
   */
  name: string;
}

export interface EmailSource {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  created_at: string;
  email_address: string;
  id: string;
  is_active: boolean;
  last_error?: string;
  last_fetched_at?: string;
  provider: string;
  token_expires_at: string;
  updated_at: string;
  user_id: string;
}

export interface ErrorDetail {
  /** Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
  location?: string;
  /** Error message text */
  message?: string;
  /** The value at the given location */
  value?: unknown;
}

/**
 * Optional list of individual error details
 */
export type ErrorModelErrors = ErrorDetail[] | null;

export interface ErrorModel {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** A human-readable explanation specific to this occurrence of the problem. */
  detail?: string;
  /** Optional list of individual error details */
  errors?: ErrorModelErrors;
  /** A URI reference that identifies the specific occurrence of the problem. */
  instance?: string;
  /** HTTP status code */
  status?: number;
  /** A short, human-readable summary of the problem type. This value should not change between occurrences of the error. */
  title?: string;
  /** A URI reference to human-readable documentation for the error. */
  type?: string;
}

export interface FeedHealthResponseBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  error_count: number;
  is_active: boolean;
  last_error?: string;
  last_polled_at?: string;
  status: string;
}

export interface FeedResponseBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  created_at: string;
  description: string;
  error_count: number;
  id: string;
  is_active: boolean;
  last_error?: string;
  last_polled_at?: string;
  poll_frequency_minutes: number;
  status: string;
  title: string;
  updated_at: string;
  url: string;
}

export interface GmailCallbackResponseBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  message: string;
  success: boolean;
}

export interface GoogleCallbackResponseBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** URL to redirect user to after authentication */
  redirect_url: string;
}

export interface GoogleLoginResponseBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Google OAuth authorization URL */
  auth_url: string;
}

export interface HealthResponseBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Database health status */
  database: string;
  /** Overall health status */
  status: string;
}

export interface Item {
  created_at: string;
  description: string;
  error_count: number;
  id: string;
  is_active: boolean;
  last_error?: string;
  last_polled_at?: string;
  poll_frequency_minutes: number;
  status: string;
  title: string;
  updated_at: string;
  url: string;
}

export interface LLMConfigResponse {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  api_url: string;
  created_at: string;
  has_api_key: boolean;
  id: string;
  model: string;
  provider: string;
  updated_at: string;
}

export type ListArticlesResponseBodyArticles = ArticleResponse[] | null;

export interface ListArticlesResponseBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  articles: ListArticlesResponseBodyArticles;
  limit: number;
  offset: number;
  total_count: number;
}

export type ListEmailSourcesResponseBodyEmailSources = EmailSource[] | null;

export interface ListEmailSourcesResponseBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  email_sources: ListEmailSourcesResponseBodyEmailSources;
}

export type ListFeedsResponseBodyFeeds = Item[] | null;

export interface ListFeedsResponseBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  feeds: ListFeedsResponseBodyFeeds;
  limit: number;
  offset: number;
  total_count: number;
}

export type ListNewsletterFiltersResponseBodyFilters = NewsletterFilter[] | null;

export interface ListNewsletterFiltersResponseBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  filters: ListNewsletterFiltersResponseBodyFilters;
}

export type ListTopicsResponseBodyTopics = TopicWithPreference[] | null;

export interface ListTopicsResponseBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  topics: ListTopicsResponseBodyTopics;
}

export type ListUsersResponseBodyUsers = UserResponse[] | null;

export interface ListUsersResponseBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  users: ListUsersResponseBodyUsers;
}

export interface MarkAsReadRequestBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Read status */
  is_read: boolean;
}

export interface MeResponseBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  created_at: string;
  email: string;
  id: string;
  name: string;
  picture_url?: string;
  role: string;
}

export interface NewsletterFilter {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  created_at: string;
  email_source_id: string;
  id: string;
  is_active: boolean;
  label_or_folder?: string;
  name: string;
  sender_pattern: string;
  subject_pattern?: string;
  updated_at: string;
  user_id: string;
}

export interface PreferencesResponse {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  created_at: string;
  default_poll_interval: number;
  id: string;
  max_articles_per_feed: number;
  updated_at: string;
  user_id: string;
}

export interface SetArchivedRequestBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Archived status */
  is_archived: boolean;
}

export interface SetSavedRequestBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Saved status */
  is_saved: boolean;
}

export interface Topic {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  created_at: string;
  id: string;
  is_custom: boolean;
  name: string;
  updated_at: string;
}

export interface TopicWithPreference {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  created_at: string;
  id: string;
  is_custom: boolean;
  name: string;
  preference: string;
  updated_at: string;
}

export interface UpdateFeedRequestBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Whether the feed is active */
  is_active?: boolean;
  /**
   * Poll frequency in minutes
   * @minimum 15
   * @maximum 1440
   */
  poll_frequency_minutes?: number;
  /** Feed title */
  title?: string;
}

/**
 * LLM provider to use
 */
export type UpdateLLMConfigRequestBodyProvider = typeof UpdateLLMConfigRequestBodyProvider[keyof typeof UpdateLLMConfigRequestBodyProvider];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateLLMConfigRequestBodyProvider = {
  openai: 'openai',
  anthropic: 'anthropic',
} as const;

export interface UpdateLLMConfigRequestBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** LLM API key (optional, only provide to update) */
  api_key?: string;
  /**
   * API URL for the LLM provider
   * @maxLength 500
   */
  api_url?: string;
  /**
   * LLM model name
   * @minLength 1
   * @maxLength 100
   */
  model?: string;
  /** LLM provider to use */
  provider?: UpdateLLMConfigRequestBodyProvider;
}

export interface UpdateNewsletterFilterRequestBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Whether filter is active */
  is_active?: boolean;
  /**
   * Gmail label or Outlook folder
   * @maxLength 255
   */
  label_or_folder?: string;
  /**
   * Filter name
   * @minLength 1
   * @maxLength 255
   */
  name?: string;
  /**
   * Sender pattern
   * @minLength 1
   * @maxLength 500
   */
  sender_pattern?: string;
  /**
   * Subject regex pattern
   * @maxLength 500
   */
  subject_pattern?: string;
}

export interface UpdatePreferencesRequestBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /**
   * Default poll interval in minutes
   * @minimum 15
   * @maximum 1440
   */
  default_poll_interval: number;
  /**
   * Maximum articles to fetch per feed per poll
   * @minimum 1
   * @maximum 100
   */
  max_articles_per_feed: number;
}

/**
 * Topic preference
 */
export type UpdateTopicPreferenceRequestBodyPreference = typeof UpdateTopicPreferenceRequestBodyPreference[keyof typeof UpdateTopicPreferenceRequestBodyPreference];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateTopicPreferenceRequestBodyPreference = {
  high: 'high',
  normal: 'normal',
  hide: 'hide',
} as const;

export interface UpdateTopicPreferenceRequestBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Topic preference */
  preference: UpdateTopicPreferenceRequestBodyPreference;
}

/**
 * User role
 */
export type UpdateUserRoleRequestBodyRole = typeof UpdateUserRoleRequestBodyRole[keyof typeof UpdateUserRoleRequestBodyRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateUserRoleRequestBodyRole = {
  user: 'user',
  admin: 'admin',
} as const;

export interface UpdateUserRoleRequestBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** User role */
  role: UpdateUserRoleRequestBodyRole;
}

export interface UserResponse {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  created_at: string;
  email: string;
  id: string;
  name: string;
  picture_url?: string;
  role: string;
  updated_at: string;
}

export interface WorkflowInfo {
  article_id?: string;
  article_title?: string;
  close_time?: string;
  execution_time_ms?: number;
  source_name?: string;
  source_type?: string;
  start_time?: string;
  status: string;
  workflow_id: string;
  workflow_type: string;
}

export type WorkflowOverviewResponseBodyRecentFailed = WorkflowInfo[] | null;

export type WorkflowOverviewResponseBodyRecentSuccess = WorkflowInfo[] | null;

export type WorkflowOverviewResponseBodyRunning = WorkflowInfo[] | null;

export interface WorkflowOverviewResponseBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  last_updated: string;
  recent_failed: WorkflowOverviewResponseBodyRecentFailed;
  recent_success: WorkflowOverviewResponseBodyRecentSuccess;
  running: WorkflowOverviewResponseBodyRunning;
  total_failed_24h: number;
  total_running: number;
  total_success_24h: number;
}

export type GoogleCallbackParams = {
/**
 * OAuth authorization code
 */
code: string;
/**
 * OAuth state token
 */
state: string;
};

export type ListArticlesParams = {
/**
 * Filter by feed ID
 */
feed_id?: string;
/**
 * Filter by email source ID
 */
email_source_id?: string;
/**
 * Minimum importance score
 * @minimum 1
 * @maximum 5
 */
min_importance?: number;
/**
 * Filter by topic
 */
topic?: string;
/**
 * Filter by read status (true/false)
 */
is_read?: string;
/**
 * Filter by saved status (true/false)
 */
is_saved?: string;
/**
 * Filter by archived status (true/false)
 */
is_archived?: string;
/**
 * Filter by processing status (pending/processing/completed/failed)
 */
processing_status?: string;
/**
 * Sort order: date (newest first) or importance (highest first)
 */
sort_by?: ListArticlesSortBy;
/**
 * Results per page
 * @maximum 100
 */
limit?: number;
/**
 * Pagination offset
 */
offset?: number;
};

export type ListArticlesSortBy = typeof ListArticlesSortBy[keyof typeof ListArticlesSortBy];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListArticlesSortBy = {
  date: 'date',
  importance: 'importance',
} as const;

export type GmailCallbackParams = {
/**
 * OAuth authorization code
 */
code: string;
/**
 * OAuth state token
 */
state: string;
};

export type ListFeedsParams = {
/**
 * Maximum number of feeds to return
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Number of feeds to skip
 * @minimum 0
 */
offset?: number;
};

export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;

/**
 * Processes the OAuth callback, creates a session, and returns redirect URL
 * @summary Handle Google OAuth callback
 */
export type googleCallbackResponse200 = {
  data: GoogleCallbackResponseBody
  status: 200
}

export type googleCallbackResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type googleCallbackResponseSuccess = (googleCallbackResponse200) & {
  headers: Headers;
};
export type googleCallbackResponseError = (googleCallbackResponseDefault) & {
  headers: Headers;
};

export type googleCallbackResponse = (googleCallbackResponseSuccess | googleCallbackResponseError)

export const getGoogleCallbackUrl = (params: GoogleCallbackParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/auth/google/callback?${stringifiedParams}` : `/auth/google/callback`
}

export const googleCallback = async (params: GoogleCallbackParams, options?: RequestInit): Promise<googleCallbackResponse> => {
  
  return customFetch<googleCallbackResponse>(getGoogleCallbackUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * Returns the Google OAuth authorization URL to redirect the user to
 * @summary Initiate Google OAuth login
 */
export type googleLoginResponse200 = {
  data: GoogleLoginResponseBody
  status: 200
}

export type googleLoginResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type googleLoginResponseSuccess = (googleLoginResponse200) & {
  headers: Headers;
};
export type googleLoginResponseError = (googleLoginResponseDefault) & {
  headers: Headers;
};

export type googleLoginResponse = (googleLoginResponseSuccess | googleLoginResponseError)

export const getGoogleLoginUrl = () => {


  

  return `/auth/google/login`
}

export const googleLogin = async ( options?: RequestInit): Promise<googleLoginResponse> => {
  
  return customFetch<googleLoginResponse>(getGoogleLoginUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * Deletes all sessions for the current user and clears the session cookie
 * @summary Logout and clear session
 */
export type logoutResponse204 = {
  data: void
  status: 204
}

export type logoutResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 204>
}
    
export type logoutResponseSuccess = (logoutResponse204) & {
  headers: Headers;
};
export type logoutResponseError = (logoutResponseDefault) & {
  headers: Headers;
};

export type logoutResponse = (logoutResponseSuccess | logoutResponseError)

export const getLogoutUrl = () => {


  

  return `/auth/logout`
}

export const logout = async ( options?: RequestInit): Promise<logoutResponse> => {
  
  return customFetch<logoutResponse>(getLogoutUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}



/**
 * Returns information about the currently authenticated user
 * @summary Get current user info
 */
export type meResponse200 = {
  data: MeResponseBody
  status: 200
}

export type meResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type meResponseSuccess = (meResponse200) & {
  headers: Headers;
};
export type meResponseError = (meResponseDefault) & {
  headers: Headers;
};

export type meResponse = (meResponseSuccess | meResponseError)

export const getMeUrl = () => {


  

  return `/auth/me`
}

export const me = async ( options?: RequestInit): Promise<meResponse> => {
  
  return customFetch<meResponse>(getMeUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * Check the health status of the API and its dependencies
 * @summary Health check
 */
export type healthCheckResponse200 = {
  data: HealthResponseBody
  status: 200
}

export type healthCheckResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type healthCheckResponseSuccess = (healthCheckResponse200) & {
  headers: Headers;
};
export type healthCheckResponseError = (healthCheckResponseDefault) & {
  headers: Headers;
};

export type healthCheckResponse = (healthCheckResponseSuccess | healthCheckResponseError)

export const getHealthCheckUrl = () => {


  

  return `/health`
}

export const healthCheck = async ( options?: RequestInit): Promise<healthCheckResponse> => {
  
  return customFetch<healthCheckResponse>(getHealthCheckUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * Get the current global LLM configuration for article summarization (admin only)
 * @summary Get global LLM configuration
 */
export type getLlmConfigResponse200 = {
  data: LLMConfigResponse
  status: 200
}

export type getLlmConfigResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type getLlmConfigResponseSuccess = (getLlmConfigResponse200) & {
  headers: Headers;
};
export type getLlmConfigResponseError = (getLlmConfigResponseDefault) & {
  headers: Headers;
};

export type getLlmConfigResponse = (getLlmConfigResponseSuccess | getLlmConfigResponseError)

export const getGetLlmConfigUrl = () => {


  

  return `/v1/admin/llm-config`
}

export const getLlmConfig = async ( options?: RequestInit): Promise<getLlmConfigResponse> => {
  
  return customFetch<getLlmConfigResponse>(getGetLlmConfigUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * Update the global LLM configuration for article summarization (admin only)
 * @summary Update global LLM configuration
 */
export type updateLlmConfigResponse200 = {
  data: LLMConfigResponse
  status: 200
}

export type updateLlmConfigResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type updateLlmConfigResponseSuccess = (updateLlmConfigResponse200) & {
  headers: Headers;
};
export type updateLlmConfigResponseError = (updateLlmConfigResponseDefault) & {
  headers: Headers;
};

export type updateLlmConfigResponse = (updateLlmConfigResponseSuccess | updateLlmConfigResponseError)

export const getUpdateLlmConfigUrl = () => {


  

  return `/v1/admin/llm-config`
}

export const updateLlmConfig = async (updateLLMConfigRequestBody: NonReadonly<UpdateLLMConfigRequestBody>, options?: RequestInit): Promise<updateLlmConfigResponse> => {
  
  return customFetch<updateLlmConfigResponse>(getUpdateLlmConfigUrl(),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateLLMConfigRequestBody,)
  }
);}



/**
 * Returns a list of all users in the system (admin only)
 * @summary List all users
 */
export type adminListUsersResponse200 = {
  data: ListUsersResponseBody
  status: 200
}

export type adminListUsersResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type adminListUsersResponseSuccess = (adminListUsersResponse200) & {
  headers: Headers;
};
export type adminListUsersResponseError = (adminListUsersResponseDefault) & {
  headers: Headers;
};

export type adminListUsersResponse = (adminListUsersResponseSuccess | adminListUsersResponseError)

export const getAdminListUsersUrl = () => {


  

  return `/v1/admin/users`
}

export const adminListUsers = async ( options?: RequestInit): Promise<adminListUsersResponse> => {
  
  return customFetch<adminListUsersResponse>(getAdminListUsersUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * Update a user's role (admin only)
 * @summary Update user role
 */
export type adminUpdateUserRoleResponse200 = {
  data: UserResponse
  status: 200
}

export type adminUpdateUserRoleResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type adminUpdateUserRoleResponseSuccess = (adminUpdateUserRoleResponse200) & {
  headers: Headers;
};
export type adminUpdateUserRoleResponseError = (adminUpdateUserRoleResponseDefault) & {
  headers: Headers;
};

export type adminUpdateUserRoleResponse = (adminUpdateUserRoleResponseSuccess | adminUpdateUserRoleResponseError)

export const getAdminUpdateUserRoleUrl = (userId: string,) => {


  

  return `/v1/admin/users/${userId}/role`
}

export const adminUpdateUserRole = async (userId: string,
    updateUserRoleRequestBody: NonReadonly<UpdateUserRoleRequestBody>, options?: RequestInit): Promise<adminUpdateUserRoleResponse> => {
  
  return customFetch<adminUpdateUserRoleResponse>(getAdminUpdateUserRoleUrl(userId),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateUserRoleRequestBody,)
  }
);}



/**
 * Get articles with optional filters and pagination
 * @summary List articles
 */
export type listArticlesResponse200 = {
  data: ListArticlesResponseBody
  status: 200
}

export type listArticlesResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type listArticlesResponseSuccess = (listArticlesResponse200) & {
  headers: Headers;
};
export type listArticlesResponseError = (listArticlesResponseDefault) & {
  headers: Headers;
};

export type listArticlesResponse = (listArticlesResponseSuccess | listArticlesResponseError)

export const getListArticlesUrl = (params?: ListArticlesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/articles?${stringifiedParams}` : `/v1/articles`
}

export const listArticles = async (params?: ListArticlesParams, options?: RequestInit): Promise<listArticlesResponse> => {
  
  return customFetch<listArticlesResponse>(getListArticlesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * Archive or unarchive multiple articles
 * @summary Bulk archive/unarchive articles
 */
export type bulkSetArchivedResponse200 = {
  data: BulkMarkReadResponseBody
  status: 200
}

export type bulkSetArchivedResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type bulkSetArchivedResponseSuccess = (bulkSetArchivedResponse200) & {
  headers: Headers;
};
export type bulkSetArchivedResponseError = (bulkSetArchivedResponseDefault) & {
  headers: Headers;
};

export type bulkSetArchivedResponse = (bulkSetArchivedResponseSuccess | bulkSetArchivedResponseError)

export const getBulkSetArchivedUrl = () => {


  

  return `/v1/articles/bulk-archive`
}

export const bulkSetArchived = async (bulkSetArchivedRequestBody: NonReadonly<BulkSetArchivedRequestBody>, options?: RequestInit): Promise<bulkSetArchivedResponse> => {
  
  return customFetch<bulkSetArchivedResponse>(getBulkSetArchivedUrl(),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      bulkSetArchivedRequestBody,)
  }
);}



/**
 * Save or unsave multiple articles
 * @summary Bulk save/unsave articles
 */
export type bulkSetSavedResponse200 = {
  data: BulkMarkReadResponseBody
  status: 200
}

export type bulkSetSavedResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type bulkSetSavedResponseSuccess = (bulkSetSavedResponse200) & {
  headers: Headers;
};
export type bulkSetSavedResponseError = (bulkSetSavedResponseDefault) & {
  headers: Headers;
};

export type bulkSetSavedResponse = (bulkSetSavedResponseSuccess | bulkSetSavedResponseError)

export const getBulkSetSavedUrl = () => {


  

  return `/v1/articles/bulk-save`
}

export const bulkSetSaved = async (bulkSetSavedRequestBody: NonReadonly<BulkSetSavedRequestBody>, options?: RequestInit): Promise<bulkSetSavedResponse> => {
  
  return customFetch<bulkSetSavedResponse>(getBulkSetSavedUrl(),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      bulkSetSavedRequestBody,)
  }
);}



/**
 * Mark multiple articles as read or unread
 * @summary Bulk mark articles as read
 */
export type bulkMarkReadResponse200 = {
  data: BulkMarkReadResponseBody
  status: 200
}

export type bulkMarkReadResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type bulkMarkReadResponseSuccess = (bulkMarkReadResponse200) & {
  headers: Headers;
};
export type bulkMarkReadResponseError = (bulkMarkReadResponseDefault) & {
  headers: Headers;
};

export type bulkMarkReadResponse = (bulkMarkReadResponseSuccess | bulkMarkReadResponseError)

export const getBulkMarkReadUrl = () => {


  

  return `/v1/articles/mark-read`
}

export const bulkMarkRead = async (bulkMarkReadRequestBody: NonReadonly<BulkMarkReadRequestBody>, options?: RequestInit): Promise<bulkMarkReadResponse> => {
  
  return customFetch<bulkMarkReadResponse>(getBulkMarkReadUrl(),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      bulkMarkReadRequestBody,)
  }
);}



/**
 * Get a specific article by ID
 * @summary Get article by ID
 */
export type getArticleResponse200 = {
  data: ArticleResponse
  status: 200
}

export type getArticleResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type getArticleResponseSuccess = (getArticleResponse200) & {
  headers: Headers;
};
export type getArticleResponseError = (getArticleResponseDefault) & {
  headers: Headers;
};

export type getArticleResponse = (getArticleResponseSuccess | getArticleResponseError)

export const getGetArticleUrl = (id: string,) => {


  

  return `/v1/articles/${id}`
}

export const getArticle = async (id: string, options?: RequestInit): Promise<getArticleResponse> => {
  
  return customFetch<getArticleResponse>(getGetArticleUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * Update the archived status of an article
 * @summary Archive/unarchive article
 */
export type setArticleArchivedResponse204 = {
  data: void
  status: 204
}

export type setArticleArchivedResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 204>
}
    
export type setArticleArchivedResponseSuccess = (setArticleArchivedResponse204) & {
  headers: Headers;
};
export type setArticleArchivedResponseError = (setArticleArchivedResponseDefault) & {
  headers: Headers;
};

export type setArticleArchivedResponse = (setArticleArchivedResponseSuccess | setArticleArchivedResponseError)

export const getSetArticleArchivedUrl = (id: string,) => {


  

  return `/v1/articles/${id}/archive`
}

export const setArticleArchived = async (id: string,
    setArchivedRequestBody: NonReadonly<SetArchivedRequestBody>, options?: RequestInit): Promise<setArticleArchivedResponse> => {
  
  return customFetch<setArticleArchivedResponse>(getSetArticleArchivedUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      setArchivedRequestBody,)
  }
);}



/**
 * Update the read status of an article
 * @summary Mark article as read/unread
 */
export type markArticleReadResponse204 = {
  data: void
  status: 204
}

export type markArticleReadResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 204>
}
    
export type markArticleReadResponseSuccess = (markArticleReadResponse204) & {
  headers: Headers;
};
export type markArticleReadResponseError = (markArticleReadResponseDefault) & {
  headers: Headers;
};

export type markArticleReadResponse = (markArticleReadResponseSuccess | markArticleReadResponseError)

export const getMarkArticleReadUrl = (id: string,) => {


  

  return `/v1/articles/${id}/read`
}

export const markArticleRead = async (id: string,
    markAsReadRequestBody: NonReadonly<MarkAsReadRequestBody>, options?: RequestInit): Promise<markArticleReadResponse> => {
  
  return customFetch<markArticleReadResponse>(getMarkArticleReadUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      markAsReadRequestBody,)
  }
);}



/**
 * Trigger processing for pending articles or retry failed articles
 * @summary Process or retry article
 */
export type processArticleResponse204 = {
  data: void
  status: 204
}

export type processArticleResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 204>
}
    
export type processArticleResponseSuccess = (processArticleResponse204) & {
  headers: Headers;
};
export type processArticleResponseError = (processArticleResponseDefault) & {
  headers: Headers;
};

export type processArticleResponse = (processArticleResponseSuccess | processArticleResponseError)

export const getProcessArticleUrl = (id: string,) => {


  

  return `/v1/articles/${id}/retry`
}

export const processArticle = async (id: string, options?: RequestInit): Promise<processArticleResponse> => {
  
  return customFetch<processArticleResponse>(getProcessArticleUrl(id),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}



/**
 * Update the saved status of an article
 * @summary Save/unsave article
 */
export type setArticleSavedResponse204 = {
  data: void
  status: 204
}

export type setArticleSavedResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 204>
}
    
export type setArticleSavedResponseSuccess = (setArticleSavedResponse204) & {
  headers: Headers;
};
export type setArticleSavedResponseError = (setArticleSavedResponseDefault) & {
  headers: Headers;
};

export type setArticleSavedResponse = (setArticleSavedResponseSuccess | setArticleSavedResponseError)

export const getSetArticleSavedUrl = (id: string,) => {


  

  return `/v1/articles/${id}/save`
}

export const setArticleSaved = async (id: string,
    setSavedRequestBody: NonReadonly<SetSavedRequestBody>, options?: RequestInit): Promise<setArticleSavedResponse> => {
  
  return customFetch<setArticleSavedResponse>(getSetArticleSavedUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      setSavedRequestBody,)
  }
);}



/**
 * Processes the Gmail OAuth callback and stores access tokens
 * @summary Handle Gmail OAuth callback
 */
export type gmailCallbackResponse200 = {
  data: GmailCallbackResponseBody
  status: 200
}

export type gmailCallbackResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type gmailCallbackResponseSuccess = (gmailCallbackResponse200) & {
  headers: Headers;
};
export type gmailCallbackResponseError = (gmailCallbackResponseDefault) & {
  headers: Headers;
};

export type gmailCallbackResponse = (gmailCallbackResponseSuccess | gmailCallbackResponseError)

export const getGmailCallbackUrl = (params: GmailCallbackParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/auth/gmail/callback?${stringifiedParams}` : `/v1/auth/gmail/callback`
}

export const gmailCallback = async (params: GmailCallbackParams, options?: RequestInit): Promise<gmailCallbackResponse> => {
  
  return customFetch<gmailCallbackResponse>(getGmailCallbackUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * Initiates OAuth flow to connect user's Gmail account
 * @summary Connect Gmail account for newsletter fetching
 */
export type connectGmailResponse200 = {
  data: ConnectGmailResponseBody
  status: 200
}

export type connectGmailResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type connectGmailResponseSuccess = (connectGmailResponse200) & {
  headers: Headers;
};
export type connectGmailResponseError = (connectGmailResponseDefault) & {
  headers: Headers;
};

export type connectGmailResponse = (connectGmailResponseSuccess | connectGmailResponseError)

export const getConnectGmailUrl = () => {


  

  return `/v1/auth/gmail/connect`
}

export const connectGmail = async ( options?: RequestInit): Promise<connectGmailResponse> => {
  
  return customFetch<connectGmailResponse>(getConnectGmailUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * Returns all email sources for the current user
 * @summary List email sources
 */
export type listEmailSourcesResponse200 = {
  data: ListEmailSourcesResponseBody
  status: 200
}

export type listEmailSourcesResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type listEmailSourcesResponseSuccess = (listEmailSourcesResponse200) & {
  headers: Headers;
};
export type listEmailSourcesResponseError = (listEmailSourcesResponseDefault) & {
  headers: Headers;
};

export type listEmailSourcesResponse = (listEmailSourcesResponseSuccess | listEmailSourcesResponseError)

export const getListEmailSourcesUrl = () => {


  

  return `/v1/email-sources`
}

export const listEmailSources = async ( options?: RequestInit): Promise<listEmailSourcesResponse> => {
  
  return customFetch<listEmailSourcesResponse>(getListEmailSourcesUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * Disconnects and deletes an email source
 * @summary Delete email source
 */
export type deleteEmailSourceResponse204 = {
  data: void
  status: 204
}

export type deleteEmailSourceResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 204>
}
    
export type deleteEmailSourceResponseSuccess = (deleteEmailSourceResponse204) & {
  headers: Headers;
};
export type deleteEmailSourceResponseError = (deleteEmailSourceResponseDefault) & {
  headers: Headers;
};

export type deleteEmailSourceResponse = (deleteEmailSourceResponseSuccess | deleteEmailSourceResponseError)

export const getDeleteEmailSourceUrl = (id: string,) => {


  

  return `/v1/email-sources/${id}`
}

export const deleteEmailSource = async (id: string, options?: RequestInit): Promise<deleteEmailSourceResponse> => {
  
  return customFetch<deleteEmailSourceResponse>(getDeleteEmailSourceUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}



/**
 * Returns a single email source by ID
 * @summary Get email source
 */
export type getEmailSourceResponse200 = {
  data: EmailSource
  status: 200
}

export type getEmailSourceResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type getEmailSourceResponseSuccess = (getEmailSourceResponse200) & {
  headers: Headers;
};
export type getEmailSourceResponseError = (getEmailSourceResponseDefault) & {
  headers: Headers;
};

export type getEmailSourceResponse = (getEmailSourceResponseSuccess | getEmailSourceResponseError)

export const getGetEmailSourceUrl = (id: string,) => {


  

  return `/v1/email-sources/${id}`
}

export const getEmailSource = async (id: string, options?: RequestInit): Promise<getEmailSourceResponse> => {
  
  return customFetch<getEmailSourceResponse>(getGetEmailSourceUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * Get all RSS feeds for the authenticated user with pagination
 * @summary List all feeds
 */
export type listFeedsResponse200 = {
  data: ListFeedsResponseBody
  status: 200
}

export type listFeedsResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type listFeedsResponseSuccess = (listFeedsResponse200) & {
  headers: Headers;
};
export type listFeedsResponseError = (listFeedsResponseDefault) & {
  headers: Headers;
};

export type listFeedsResponse = (listFeedsResponseSuccess | listFeedsResponseError)

export const getListFeedsUrl = (params?: ListFeedsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/feeds?${stringifiedParams}` : `/v1/feeds`
}

export const listFeeds = async (params?: ListFeedsParams, options?: RequestInit): Promise<listFeedsResponse> => {
  
  return customFetch<listFeedsResponse>(getListFeedsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * Add a new RSS feed for the authenticated user
 * @summary Create a new RSS feed
 */
export type createFeedResponse200 = {
  data: FeedResponseBody
  status: 200
}

export type createFeedResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type createFeedResponseSuccess = (createFeedResponse200) & {
  headers: Headers;
};
export type createFeedResponseError = (createFeedResponseDefault) & {
  headers: Headers;
};

export type createFeedResponse = (createFeedResponseSuccess | createFeedResponseError)

export const getCreateFeedUrl = () => {


  

  return `/v1/feeds`
}

export const createFeed = async (createFeedRequestBody: NonReadonly<CreateFeedRequestBody>, options?: RequestInit): Promise<createFeedResponse> => {
  
  return customFetch<createFeedResponse>(getCreateFeedUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createFeedRequestBody,)
  }
);}



/**
 * Delete an RSS feed and all its articles
 * @summary Delete a feed
 */
export type deleteFeedResponse204 = {
  data: void
  status: 204
}

export type deleteFeedResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 204>
}
    
export type deleteFeedResponseSuccess = (deleteFeedResponse204) & {
  headers: Headers;
};
export type deleteFeedResponseError = (deleteFeedResponseDefault) & {
  headers: Headers;
};

export type deleteFeedResponse = (deleteFeedResponseSuccess | deleteFeedResponseError)

export const getDeleteFeedUrl = (id: string,) => {


  

  return `/v1/feeds/${id}`
}

export const deleteFeed = async (id: string, options?: RequestInit): Promise<deleteFeedResponse> => {
  
  return customFetch<deleteFeedResponse>(getDeleteFeedUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}



/**
 * Get a specific RSS feed by ID
 * @summary Get feed by ID
 */
export type getFeedResponse200 = {
  data: FeedResponseBody
  status: 200
}

export type getFeedResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type getFeedResponseSuccess = (getFeedResponse200) & {
  headers: Headers;
};
export type getFeedResponseError = (getFeedResponseDefault) & {
  headers: Headers;
};

export type getFeedResponse = (getFeedResponseSuccess | getFeedResponseError)

export const getGetFeedUrl = (id: string,) => {


  

  return `/v1/feeds/${id}`
}

export const getFeed = async (id: string, options?: RequestInit): Promise<getFeedResponse> => {
  
  return customFetch<getFeedResponse>(getGetFeedUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * Update feed settings
 * @summary Update a feed
 */
export type updateFeedResponse200 = {
  data: FeedResponseBody
  status: 200
}

export type updateFeedResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type updateFeedResponseSuccess = (updateFeedResponse200) & {
  headers: Headers;
};
export type updateFeedResponseError = (updateFeedResponseDefault) & {
  headers: Headers;
};

export type updateFeedResponse = (updateFeedResponseSuccess | updateFeedResponseError)

export const getUpdateFeedUrl = (id: string,) => {


  

  return `/v1/feeds/${id}`
}

export const updateFeed = async (id: string,
    updateFeedRequestBody: NonReadonly<UpdateFeedRequestBody>, options?: RequestInit): Promise<updateFeedResponse> => {
  
  return customFetch<updateFeedResponse>(getUpdateFeedUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateFeedRequestBody,)
  }
);}



/**
 * Get the health status and error information for a feed
 * @summary Get feed health
 */
export type getFeedHealthResponse200 = {
  data: FeedHealthResponseBody
  status: 200
}

export type getFeedHealthResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type getFeedHealthResponseSuccess = (getFeedHealthResponse200) & {
  headers: Headers;
};
export type getFeedHealthResponseError = (getFeedHealthResponseDefault) & {
  headers: Headers;
};

export type getFeedHealthResponse = (getFeedHealthResponseSuccess | getFeedHealthResponseError)

export const getGetFeedHealthUrl = (id: string,) => {


  

  return `/v1/feeds/${id}/health`
}

export const getFeedHealth = async (id: string, options?: RequestInit): Promise<getFeedHealthResponse> => {
  
  return customFetch<getFeedHealthResponse>(getGetFeedHealthUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * Trigger an immediate poll of the feed
 * @summary Manually refresh a feed
 */
export type refreshFeedResponse204 = {
  data: void
  status: 204
}

export type refreshFeedResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 204>
}
    
export type refreshFeedResponseSuccess = (refreshFeedResponse204) & {
  headers: Headers;
};
export type refreshFeedResponseError = (refreshFeedResponseDefault) & {
  headers: Headers;
};

export type refreshFeedResponse = (refreshFeedResponseSuccess | refreshFeedResponseError)

export const getRefreshFeedUrl = (id: string,) => {


  

  return `/v1/feeds/${id}/refresh`
}

export const refreshFeed = async (id: string, options?: RequestInit): Promise<refreshFeedResponse> => {
  
  return customFetch<refreshFeedResponse>(getRefreshFeedUrl(id),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}



/**
 * Query Temporal for running and recent workflows with article details
 * @summary Get Temporal workflow overview
 */
export type getWorkflowOverviewResponse200 = {
  data: WorkflowOverviewResponseBody
  status: 200
}

export type getWorkflowOverviewResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type getWorkflowOverviewResponseSuccess = (getWorkflowOverviewResponse200) & {
  headers: Headers;
};
export type getWorkflowOverviewResponseError = (getWorkflowOverviewResponseDefault) & {
  headers: Headers;
};

export type getWorkflowOverviewResponse = (getWorkflowOverviewResponseSuccess | getWorkflowOverviewResponseError)

export const getGetWorkflowOverviewUrl = () => {


  

  return `/v1/monitoring/workflows`
}

export const getWorkflowOverview = async ( options?: RequestInit): Promise<getWorkflowOverviewResponse> => {
  
  return customFetch<getWorkflowOverviewResponse>(getGetWorkflowOverviewUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * Returns all newsletter filters for the current user
 * @summary List newsletter filters
 */
export type listNewsletterFiltersResponse200 = {
  data: ListNewsletterFiltersResponseBody
  status: 200
}

export type listNewsletterFiltersResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type listNewsletterFiltersResponseSuccess = (listNewsletterFiltersResponse200) & {
  headers: Headers;
};
export type listNewsletterFiltersResponseError = (listNewsletterFiltersResponseDefault) & {
  headers: Headers;
};

export type listNewsletterFiltersResponse = (listNewsletterFiltersResponseSuccess | listNewsletterFiltersResponseError)

export const getListNewsletterFiltersUrl = () => {


  

  return `/v1/newsletter-filters`
}

export const listNewsletterFilters = async ( options?: RequestInit): Promise<listNewsletterFiltersResponse> => {
  
  return customFetch<listNewsletterFiltersResponse>(getListNewsletterFiltersUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * Creates a new filter for identifying newsletters
 * @summary Create newsletter filter
 */
export type createNewsletterFilterResponse200 = {
  data: NewsletterFilter
  status: 200
}

export type createNewsletterFilterResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type createNewsletterFilterResponseSuccess = (createNewsletterFilterResponse200) & {
  headers: Headers;
};
export type createNewsletterFilterResponseError = (createNewsletterFilterResponseDefault) & {
  headers: Headers;
};

export type createNewsletterFilterResponse = (createNewsletterFilterResponseSuccess | createNewsletterFilterResponseError)

export const getCreateNewsletterFilterUrl = () => {


  

  return `/v1/newsletter-filters`
}

export const createNewsletterFilter = async (createNewsletterFilterRequestBody: NonReadonly<CreateNewsletterFilterRequestBody>, options?: RequestInit): Promise<createNewsletterFilterResponse> => {
  
  return customFetch<createNewsletterFilterResponse>(getCreateNewsletterFilterUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createNewsletterFilterRequestBody,)
  }
);}



/**
 * Deletes a newsletter filter
 * @summary Delete newsletter filter
 */
export type deleteNewsletterFilterResponse204 = {
  data: void
  status: 204
}

export type deleteNewsletterFilterResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 204>
}
    
export type deleteNewsletterFilterResponseSuccess = (deleteNewsletterFilterResponse204) & {
  headers: Headers;
};
export type deleteNewsletterFilterResponseError = (deleteNewsletterFilterResponseDefault) & {
  headers: Headers;
};

export type deleteNewsletterFilterResponse = (deleteNewsletterFilterResponseSuccess | deleteNewsletterFilterResponseError)

export const getDeleteNewsletterFilterUrl = (id: string,) => {


  

  return `/v1/newsletter-filters/${id}`
}

export const deleteNewsletterFilter = async (id: string, options?: RequestInit): Promise<deleteNewsletterFilterResponse> => {
  
  return customFetch<deleteNewsletterFilterResponse>(getDeleteNewsletterFilterUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}



/**
 * Returns a single newsletter filter by ID
 * @summary Get newsletter filter
 */
export type getNewsletterFilterResponse200 = {
  data: NewsletterFilter
  status: 200
}

export type getNewsletterFilterResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type getNewsletterFilterResponseSuccess = (getNewsletterFilterResponse200) & {
  headers: Headers;
};
export type getNewsletterFilterResponseError = (getNewsletterFilterResponseDefault) & {
  headers: Headers;
};

export type getNewsletterFilterResponse = (getNewsletterFilterResponseSuccess | getNewsletterFilterResponseError)

export const getGetNewsletterFilterUrl = (id: string,) => {


  

  return `/v1/newsletter-filters/${id}`
}

export const getNewsletterFilter = async (id: string, options?: RequestInit): Promise<getNewsletterFilterResponse> => {
  
  return customFetch<getNewsletterFilterResponse>(getGetNewsletterFilterUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * Updates an existing newsletter filter
 * @summary Update newsletter filter
 */
export type updateNewsletterFilterResponse200 = {
  data: NewsletterFilter
  status: 200
}

export type updateNewsletterFilterResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type updateNewsletterFilterResponseSuccess = (updateNewsletterFilterResponse200) & {
  headers: Headers;
};
export type updateNewsletterFilterResponseError = (updateNewsletterFilterResponseDefault) & {
  headers: Headers;
};

export type updateNewsletterFilterResponse = (updateNewsletterFilterResponseSuccess | updateNewsletterFilterResponseError)

export const getUpdateNewsletterFilterUrl = (id: string,) => {


  

  return `/v1/newsletter-filters/${id}`
}

export const updateNewsletterFilter = async (id: string,
    updateNewsletterFilterRequestBody: NonReadonly<UpdateNewsletterFilterRequestBody>, options?: RequestInit): Promise<updateNewsletterFilterResponse> => {
  
  return customFetch<updateNewsletterFilterResponse>(getUpdateNewsletterFilterUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateNewsletterFilterRequestBody,)
  }
);}



/**
 * Get all topics from user's subscribed feeds with their preferences
 * @summary List topics
 */
export type listTopicsResponse200 = {
  data: ListTopicsResponseBody
  status: 200
}

export type listTopicsResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type listTopicsResponseSuccess = (listTopicsResponse200) & {
  headers: Headers;
};
export type listTopicsResponseError = (listTopicsResponseDefault) & {
  headers: Headers;
};

export type listTopicsResponse = (listTopicsResponseSuccess | listTopicsResponseError)

export const getListTopicsUrl = () => {


  

  return `/v1/topics`
}

export const listTopics = async ( options?: RequestInit): Promise<listTopicsResponse> => {
  
  return customFetch<listTopicsResponse>(getListTopicsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * Create a new custom topic
 * @summary Create custom topic
 */
export type createTopicResponse200 = {
  data: Topic
  status: 200
}

export type createTopicResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type createTopicResponseSuccess = (createTopicResponse200) & {
  headers: Headers;
};
export type createTopicResponseError = (createTopicResponseDefault) & {
  headers: Headers;
};

export type createTopicResponse = (createTopicResponseSuccess | createTopicResponseError)

export const getCreateTopicUrl = () => {


  

  return `/v1/topics`
}

export const createTopic = async (createTopicRequestBody: NonReadonly<CreateTopicRequestBody>, options?: RequestInit): Promise<createTopicResponse> => {
  
  return customFetch<createTopicResponse>(getCreateTopicUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createTopicRequestBody,)
  }
);}



/**
 * Delete a custom topic (only if it has no user preferences)
 * @summary Delete custom topic
 */
export type deleteTopicResponse204 = {
  data: void
  status: 204
}

export type deleteTopicResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 204>
}
    
export type deleteTopicResponseSuccess = (deleteTopicResponse204) & {
  headers: Headers;
};
export type deleteTopicResponseError = (deleteTopicResponseDefault) & {
  headers: Headers;
};

export type deleteTopicResponse = (deleteTopicResponseSuccess | deleteTopicResponseError)

export const getDeleteTopicUrl = (id: string,) => {


  

  return `/v1/topics/${id}`
}

export const deleteTopic = async (id: string, options?: RequestInit): Promise<deleteTopicResponse> => {
  
  return customFetch<deleteTopicResponse>(getDeleteTopicUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}



/**
 * Get a specific topic with user's preference
 * @summary Get topic by ID
 */
export type getTopicResponse200 = {
  data: TopicWithPreference
  status: 200
}

export type getTopicResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type getTopicResponseSuccess = (getTopicResponse200) & {
  headers: Headers;
};
export type getTopicResponseError = (getTopicResponseDefault) & {
  headers: Headers;
};

export type getTopicResponse = (getTopicResponseSuccess | getTopicResponseError)

export const getGetTopicUrl = (id: string,) => {


  

  return `/v1/topics/${id}`
}

export const getTopic = async (id: string, options?: RequestInit): Promise<getTopicResponse> => {
  
  return customFetch<getTopicResponse>(getGetTopicUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * Update the user's preference for a topic
 * @summary Update topic preference
 */
export type updateTopicPreferenceResponse200 = {
  data: TopicWithPreference
  status: 200
}

export type updateTopicPreferenceResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type updateTopicPreferenceResponseSuccess = (updateTopicPreferenceResponse200) & {
  headers: Headers;
};
export type updateTopicPreferenceResponseError = (updateTopicPreferenceResponseDefault) & {
  headers: Headers;
};

export type updateTopicPreferenceResponse = (updateTopicPreferenceResponseSuccess | updateTopicPreferenceResponseError)

export const getUpdateTopicPreferenceUrl = (id: string,) => {


  

  return `/v1/topics/${id}/preference`
}

export const updateTopicPreference = async (id: string,
    updateTopicPreferenceRequestBody: NonReadonly<UpdateTopicPreferenceRequestBody>, options?: RequestInit): Promise<updateTopicPreferenceResponse> => {
  
  return customFetch<updateTopicPreferenceResponse>(getUpdateTopicPreferenceUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateTopicPreferenceRequestBody,)
  }
);}



/**
 * Get the current user's preferences
 * @summary Get user preferences
 */
export type getUserPreferencesResponse200 = {
  data: PreferencesResponse
  status: 200
}

export type getUserPreferencesResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type getUserPreferencesResponseSuccess = (getUserPreferencesResponse200) & {
  headers: Headers;
};
export type getUserPreferencesResponseError = (getUserPreferencesResponseDefault) & {
  headers: Headers;
};

export type getUserPreferencesResponse = (getUserPreferencesResponseSuccess | getUserPreferencesResponseError)

export const getGetUserPreferencesUrl = () => {


  

  return `/v1/user/preferences`
}

export const getUserPreferences = async ( options?: RequestInit): Promise<getUserPreferencesResponse> => {
  
  return customFetch<getUserPreferencesResponse>(getGetUserPreferencesUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * Update the current user's preferences
 * @summary Update user preferences
 */
export type updateUserPreferencesResponse200 = {
  data: PreferencesResponse
  status: 200
}

export type updateUserPreferencesResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type updateUserPreferencesResponseSuccess = (updateUserPreferencesResponse200) & {
  headers: Headers;
};
export type updateUserPreferencesResponseError = (updateUserPreferencesResponseDefault) & {
  headers: Headers;
};

export type updateUserPreferencesResponse = (updateUserPreferencesResponseSuccess | updateUserPreferencesResponseError)

export const getUpdateUserPreferencesUrl = () => {


  

  return `/v1/user/preferences`
}

export const updateUserPreferences = async (updatePreferencesRequestBody: NonReadonly<UpdatePreferencesRequestBody>, options?: RequestInit): Promise<updateUserPreferencesResponse> => {
  
  return customFetch<updateUserPreferencesResponse>(getUpdateUserPreferencesUrl(),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updatePreferencesRequestBody,)
  }
);}
